version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: feedback-backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
      - JAVA_OPTS=${JAVA_OPTS:-}
      - H2_CONSOLE_WEB_ALLOW_OTHERS=${H2_CONSOLE_WEB_ALLOW_OTHERS:-true}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge