server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:feedbackdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: ${H2_CONSOLE_WEB_ALLOW_OTHERS:false}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO
    com.example.feedback: INFO

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}